package com.gyeonglodang.mybatis.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.gyeonglodang.dto.ApplicantDTO;
import com.gyeonglodang.dto.GetCareerDTO;
import com.gyeonglodang.dto.GetCareerQDTO;
import com.gyeonglodang.dto.GetFileValueDTO;
import com.gyeonglodang.dto.GetFileValueFinalDTO;
import com.gyeonglodang.dto.GetInfoDTO;
import com.gyeonglodang.dto.GetInfoValueDTO;
import com.gyeonglodang.dto.GetInfoValueFinalDTO;
import com.gyeonglodang.dto.GetPersonalCustomDTO;
import com.gyeonglodang.dto.GetPersonalDTO;
import com.gyeonglodang.dto.GetPersonalQDTO;
import com.gyeonglodang.dto.GetResumeCustomDTO;
import com.gyeonglodang.dto.GetSentenceTypeDTO;
import com.gyeonglodang.dto.GetTableTypeDTO;
import com.gyeonglodang.dto.GetTableTypeQDTO;
import com.gyeonglodang.dto.JobNoticeDTO;
import com.gyeonglodang.dto.RecruitCateg_boardDTO;
import com.gyeonglodang.dto.ResumeFileUploadSetDTO;
import com.gyeonglodang.dto.RsmFileDTO;
@Mapper
public interface RecruitResumeMapper {
	public List<JobNoticeDTO> getTitle(int companyIdx);
	public ApplicantDTO getApplicant(String email);
	public ApplicantDTO getApplicant2(Map<String,Object> map);
	public int insertApplicant(ApplicantDTO dto);
	public List<JobNoticeDTO> getJobNoticeList(Map<String,Object> map);
	public String getJBTittle(int noticeControl_idx);
	public GetPersonalDTO getPersonalList(int personalidx);
	public int insertPersonalValue(Map<String, Object> map);
	public GetCareerDTO getCareerList(int careeridx);
	public GetPersonalCustomDTO getPersonalCustom(int infocustomidx);
	public GetResumeCustomDTO getResumeCustom(int resumecustomidx);
	public List<GetSentenceTypeDTO> getSentenceType(int resumeCustomIdx);
	public List<GetTableTypeDTO> getTableTypeList(int resumeCustomIdx);
	public int insert_infocustom(Map<String, Object> insertMap);
	public int insert_setence(Map<String, Object> insertMap);
	public int insert_table(Map<String, Object> insertMap);
	public int insert_info(Map<String, Object> infoMap);
	public List<GetTableTypeQDTO> getTableTypeQListAll();
	public List<GetPersonalQDTO> getPersonalQList();
	public List<GetCareerQDTO> getCareerQList();
	public GetInfoDTO getInfo(int noticeControl_idx);
	public List<String> getPersonalValueList(Map<String, Object> applicant_info);
	public int insertCareerValue(Map<String, Object> insertMap);
	public List<String> getCareerValueList(Map<String, Object> applicant_info);
	public List<String> getInfoCustomValueList(Map<String, Object> applicant_info);
	public int deletePersonalValue(Map<String, Object> applicant_info);
	public int deleteCareerValue(Map<String, Object> applicant_info);
	public int deleteSentenceValue(Map<String, Object> applicant_info);
	public int deleteInfoCustomValue(Map<String, Object> applicant_info);
	public int deleteTableValue(Map<String, Object> applicant_info);
	public int deleteInfoValue(Map<String, Object> applicant_info);
	public int deleteResumeFile(Map<String, Object> applicant_info);
	public List<String> getSentenceValueList(Map<String, Object> applicant_info);
	public List<String> gettableValueList(Map<String, Object> applicant_info);
	public GetInfoValueDTO getinfoValue(Map<String, Object> applicant_info);
	public List<GetFileValueDTO> getFileValueList(Map<String, Object> applicant_info);
	public List<Integer> getInfoCustomIdxList(Map<String, Object> application_info);
	public List<Integer> getPersonalIdxList(Map<String, Object> application_info);
	public List<Integer> getCareerIdxList(Map<String, Object> application_info);
	public List<Integer> getResumeCustomIdxList(Map<String, Object> application_info);
	public List<Integer> getFileIdxList(Map<String, Object> application_info);
	public RsmFileDTO getResumeFile(int noticeControl_idx);
	public ResumeFileUploadSetDTO getRsmFileUpload(int fileidx);
	public int insertResumeFile(Map<String, Object> fileUploadmap);
	public int insertPersonalValue_final(Map<String, Object> insertMap);
	public int insertCareerValue_final(Map<String, Object> insertMap);
	public int insert_final_infocustom(Map<String, Object> insertMap);
	public int insert_final_sentence(Map<String, Object> insertMap);
	public int insert_final_table(Map<String, Object> insertMap);
	public int insert_final_info(Map<String, Object> infoMap);
	public int insertResumeFile_final(Map<String, Object> fileUploadmap);
	public List<String> getPersonalValueList_final(Map<String, Object> applicant_info);
	public List<String> getCareerValueList_final(Map<String, Object> applicant_info);
	public List<String> getInfoCustomValueList_final(Map<String, Object> applicant_info);
	public List<String> getSentenceValueList_final(Map<String, Object> applicant_info);
	public List<String> gettableValueList_final(Map<String, Object> applicant_info);
	public GetInfoValueFinalDTO getinfoValue_final(Map<String, Object> applicant_info);
	public List<GetFileValueFinalDTO> getFileValueList_final(Map<String, Object> applicant_info);
	public List<RecruitCateg_boardDTO> getField(RecruitCateg_boardDTO categ);
	public int updateField(Map<String,Object> map);
	public int updateScode(Map<String,Object> map);
	public String getFieldCode(Map<String,Object> map);
	public String getCountScode(int noticeControl_idx);
	public Map<String, Object> getCategScode(Map<String, Object> map);
}